name: RandomFishing
author: Cristichi
version: 1.5
main: com.cristichidnk.pescalocke.Main
commands:
   giveRandomRod:
      description: Gives you or given player the Random Fishing Rod
      permission: pescalocke.give.randomrod
      usage: /giveRandomRod {Player}
   giveRenameRod:
      description: Gives you or given player the Renamer Fishing Rod
      permission: pescalocke.give.renamerod
      usage: /giveRenameRod {Player}
   giveMountRods:
      description: Gives you or given player both Mounts Fishing Rods
      permission: pescalocke.give.mountrods
      usage: /giveMountRods {Player}
permissions:
    pescalocke:
        description: All Pescalocke permissions
        children:
            pescalocke.give.randomrod: true
            pescalocke.give.renamerod: true
            pescalocke.give.mountrods: true
    pescalocke.give.randomrod:
        description: Lets you use /giveRandomRod
        default: op
    pescalocke.give.renamerod:
        description: Lets you use /giveRenameRod
        default: op
    pescalocke.give.mountrods:
        description: Lets you use /giveMountRods
        default: op
